@isTest
public with sharing class NextPolicyRec{
public List<String> records{get;set;}

public NextPolicyRec()
{
    records = new List<String>();
    records.add('rec1');
    records.add('rec2');
    records.add('rec3');
    records.add('rec4');
    records.add('rec5');
    records.add('rec6');
    records.add('rec7');
    records.add('rec8');
    records.add('rec9');
    records.add('rec10');
    records.add('rec11');
    records.add('rec12');
}
}