/*
 * TCIStatics
 * TCI Static Values commonly used.
 */

public abstract class TCIStatics {
	// status components
	public static final String STATUS_DRAFT = 'Draft';
	public static final String STATUS_COMPLETE = 'Complete';
	public static final String STATUS_PENDING = 'Pending';
	public static final String STATUS_IN_PROGRESS = 'In Progress';
	public static final String STATUS_ACTIVE = 'Active';
	public static final String STATUS_INACTIVE = 'Inactive';
	public static final String DRIVER_STATUS_RATED = 'Rated';
	
	// error message components
	public static final String NO_ACCESS = 'You do not have permission to access this information';

	// record type values
	public static final String RT_SPOUSE = 'Spouse';
	public static final String RT_COUSIN = 'Cousin';
	public static final String RT_PARENT = 'Parent';
	public static final String RT_AUTO = 'Auto';
	public static final String RT_RENTERS = 'Renters';
	public static final String RT_HOMEONWERS = 'Homeowners';
	public static final String RT_COMMERCIAL = 'Commercial';

	// address validations
	public static final String MAILINGSTATUS_CONFIRMED = 'Confirmed';
	public static final String MAILINGSTATUS_NOT_SUBMITTED = 'Not Submitted';
	public static final String MAILINGSTATUS_NOT_CONFIRMED = 'Not Confirmed';

	// driver validations
	public static final String LICENSE_STATUS = 'Valid';

}